In [1]:
import numpy as np
import matplotlib.pyplot as plt

In [2]:
X = np.array([[1, 1, 1, 1, 1,
               1, 1, 1, 1, 1],
              [1, 1, 2, 1, 3, 
               0, 5, 10, 1, 2]])

y = [45, 55, 50, 59, 65,
    35, 75, 80, 50, 60]

In [3]:
def calc_mse(y, y_pred):
  err = np.mean((y - y_pred)**2)
  return err

In [4]:
def calc_mae(y, y_pred):
  err = np.mean(np.abs(y - y_pred))
  return err

## Задание 1. Подберите скорость обучения (alpha) и количество итераций

In [5]:
n = X.shape[1]
alpha = 1e-2
W = np.array([1, 0.5])
W, alpha

(array([1. , 0.5]), 0.01)

In [6]:
for i in range(640):
    y_pred = np.dot(W, X)
    err = calc_mse(y, y_pred)
    
    for ii in range(W.shape[0]):
        W[ii] -= alpha * (1/n * 2 * np.sum(X[ii] * (y_pred - y)))
    
    if i % 10 == 0:
        print(i, W, err)

0 [2.102 3.9  ] 3173.15
10 [ 7.88197949 10.94665576] 895.7992568721307
20 [11.82321845 10.44288316] 734.1943046789495
30 [15.33838126  9.79996576] 604.3598272772635
40 [18.50371626  9.21563317] 499.01844357436784
50 [21.35487986  8.68914872] 413.5487715072509
60 [23.92307798  8.21491142] 344.2021894686833
70 [26.23639435  7.78773986] 287.93722057193975
80 [28.32012482  7.40296309] 242.28613537222674
90 [30.19705472  7.05637362] 205.24671953719772
100 [31.88770806  6.74418155] 175.19445858001853
110 [33.4105719   6.46297309] 150.81128815797626
120 [34.78229859  6.20967327] 131.0277849906938
130 [36.01788778  5.98151227] 114.97626294514153
140 [37.13085048  5.7759952 ] 101.95271712515977
150 [38.13335681  5.59087473] 91.38594686849362
160 [39.03636904  5.42412662] 82.8125034145725
170 [39.8497615   5.27392748] 75.85636347094018
180 [40.58242855  5.1386349 ] 70.21243717977558
190 [41.24238179  5.01676949] 65.63318715918639
200 [41.83683774  4.90699865] 61.9177717428135
210 [42.3722967   4

## Задание 2. В этом коде мы избавляемся от итераций по весам, но тут есть ошибка, исправьте ее

In [7]:
n = X.shape[1]
alpha = 1e-2
W = np.array([1, 0.5])
W, alpha

(array([1. , 0.5]), 0.01)

In [8]:
# необходимо было добавить параметр axis в np.sum
for i in range(640):
    y_pred = np.dot(W, X)
    err = calc_mse(y, y_pred)

    W -= alpha * (1/n * 2 * np.sum(X * (y_pred - y), axis=1))

    if i % 10 == 0:
        print(i, W, err)

0 [2.102 3.9  ] 3173.15
10 [ 7.88197949 10.94665576] 895.7992568721307
20 [11.82321845 10.44288316] 734.1943046789495
30 [15.33838126  9.79996576] 604.3598272772635
40 [18.50371626  9.21563317] 499.01844357436784
50 [21.35487986  8.68914872] 413.5487715072509
60 [23.92307798  8.21491142] 344.2021894686833
70 [26.23639435  7.78773986] 287.93722057193975
80 [28.32012482  7.40296309] 242.28613537222674
90 [30.19705472  7.05637362] 205.24671953719772
100 [31.88770806  6.74418155] 175.19445858001853
110 [33.4105719   6.46297309] 150.81128815797626
120 [34.78229859  6.20967327] 131.0277849906938
130 [36.01788778  5.98151227] 114.97626294514153
140 [37.13085048  5.7759952 ] 101.95271712515977
150 [38.13335681  5.59087473] 91.38594686849362
160 [39.03636904  5.42412662] 82.8125034145725
170 [39.8497615   5.27392748] 75.85636347094018
180 [40.58242855  5.1386349 ] 70.21243717977558
190 [41.24238179  5.01676949] 65.63318715918639
200 [41.83683774  4.90699865] 61.9177717428135
210 [42.3722967   4

## Задание 3. вместо того, чтобы задавать количество итераций, задайте условие остановки алгоритма - когда ошибка за итерацию начинает изменяться ниже определенного порога (упрощенный аналог параметра tol в линейной регрессии в sklearn).

In [9]:
n = X.shape[1]
alpha = 1e-2
W = np.array([1, 0.5])
tol = 2.8e-05
W, alpha

(array([1. , 0.5]), 0.01)

In [10]:
i, prev = 0, 0
while True:
    y_pred = np.dot(W, X)

    err = calc_mse(y, y_pred)

    W -= alpha * (1/n * 2 * np.sum(X * (y_pred - y), axis=1))

    i += 1
    if i % 10 == 0:
        print(i, W, err, prev, prev - err)

    if prev > 0 and prev - err < tol:
        break

    prev = err

10 [ 7.45119279 10.92672004] 915.3849211067269 937.0990290056232 21.71410789889626
20 [11.45069652 10.50892568] 748.7346321280653 763.5834236832634 14.84879155519809
30 [15.00325863  9.8617729 ] 616.1562224022761 628.2018115086273 12.045589106351258
40 [18.20186481  9.27137026] 508.589553366367 518.362848097474 9.773294731106944
50 [21.08298609  8.73935593] 421.31437694708603 429.2440269430093 7.929649995923285
60 [23.67816841  8.26013584] 350.5028828221593 356.9366751918322 6.433792369672915
70 [26.01579092  7.82847597] 293.0493444162569 298.26945933650507 5.220114920248193
80 [28.12141525  7.43965633] 246.43390272630958 250.66928960466856 4.23538687835898
90 [30.01806616  7.08942523] 208.61204763712644 212.04846662089147 3.436418983765037
100 [31.72648327  6.77395294] 177.92494760058077 180.71311684488737 2.7881692443066015
110 [33.26534793  6.48978981] 153.02669481968303 155.2889008462543 2.2622060265712776
120 [34.65148742  6.23382855] 132.82527497866823 134.66073604944265 1.835461